- name: Update web servers
  hosts: webservers
  become: yes

  tasks:
  - name: comment line "here should be commented"
    replace:
      path: "{{ home_dir }}/test.txt" 
      regexp: '(.*should be commented.*)'
      replace: '#\1'