- name: Update apt-get repo and cache
  apt: 
    update_cache: yes 
    force_apt_get: yes
    cache_valid_time: 3600

- name: Ensure nginx is at the latest version
  apt:
    name: nginx
    state: latest

- name: create http root dir for all vhosts
  file:
    path: "{{ server.http_root_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
  loop: "{{ servers }}"
  loop_control:
    label: "{{ server.name }}"
    loop_var: server